#!/bin/bash
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# #                                                                                     # #
# #    Use Raspberry Pi Imager  (https://www.raspberrypi.com/software/)                 # #
# #    * CHOOSE DEVICE                                                                  # #
# #      Select your device                                                             # #
# #    * CHOOSE OS                                                                      # #
# #      Select Raspberry Pi OS (other)                                                 # #
# #      Select Raspberry Pi OS (Legacy, 32-bit) Lite                                   # #
# #    * CHOOSE STORAGE                                                                 # #
# #      Select your storage device                                                     # #
# #    * NEXT                                                                           # #
# #                                                                                     # #
# #    * EDIT SETTINGS                                                                  # #
# #    * Set hostname                                                                   # #
# #    * Set username and password                                                      # #
# #    ! DO NOT CONFIGURE wireless LAN !   see notes below                              # #
# #    * Set locale settings                                                            # #
# #    Select Time zone                                                                 # #
# #    Select Keyboard layout                                                           # #
# #    * SERVICES                                                                       # #
# #    * Enable SSH                                                                     # #
# #    * Allow public-key authentication only                                           # #
# #    Set authorized_key for 'user'                                                    # #
# #    * SAVE                                                                           # #
# #    * YES                                                                            # #
# #                                                                                     # #
# #    Place micro SD in Raspberry Pi                                                   # #
# #    Connect network, HDMI & power                                                    # #
# #    Connect to IP via SSH                                                            # #
# #                                                                                     # #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# #                                                                                     # #
# #    NOTES                                                                            # #
# #    ---                                                                              # #
# #    If you want to change the image location change image/_LOGO_.png                 # #
# #    basketclockthread.py                                                             # #
# #    line 25                                                                          # #
# #    LogoClub = pygame.image.load('image/_LOGO_.png')                                 # #
# #    ---                                                                              # #
# #    Make sure the IPv4 address is the same in both files listed below                # #
# #    basketclockthread.py                                                             # #
# #    line 255                                                                         # #
# #       serv.bind(('10.3.141.1', 8080))                                               # #
# #    pycom/main.py                                                                    # #
# #    line 28                                                                          # #
# #       client.connect(('10.3.141.1', 8080))                                          # #
# #    ---                                                                              # #
# #    _wifi_SSID_ and _wifi_PASSWORD_ are created in the RASPAP setup below            # #
# #    Make sure the _wifi_SSID_ is unique for its location                             # #
# #    pycom/boot.py                                                                    # #
# #    line 20                                                                          # #
# #       wlan.connect('_wifi_SSID_', auth=(WLAN.WPA2, '_wifi_PASS_'), timeout=5000)    # #
# #    ---                                                                              # #
# #    Alter the username in basketclock.service in the script below on line 100
# #    to the one used in Raspberry Pi Imager                                           # #
# #    ---                                                                              # #
# #    Connect to wifi-network raspi-webgui                                             # #
# #    See https://docs.raspap.com/ap-basics/                                           # #
# #    Change the SSID, and secret.  Also update the admin password.
# #    ---                                                                              # #
# #    Make sure to run this command via SSH after the script has run                   # #
# #    sudo mount -o remount,ro /boot                                                   # #
# #    sudo raspi-config nonint enable_bootro                                           # #
# #                                                                                     # #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

## Change the URL to the project URL
URL=https://raw.githubusercontent.com/HenkUyttenhove/basketclock/test

## Make sure the system is up to date
sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get autoclean
sudo apt-get autoremove

## Important changes
sudo raspi-config nonint enable_overlayfs
sudo raspi-config nonint do_resolution 1280 768
sudo raspi-config nonint do_wifi_country BE

## Create program directories
sudo mkdir /opt/basketclock /opt/basketclock/fonts /opt/basketclock/image /opt/basketclock/sounds

## Download program files
sudo curl $URL/basketclockthread.py -o /opt/basketclock/basketclockthread.py
sudo curl $URL/fonts/DejaVuSans-Bold.ttf -o /opt/basketclock/fonts/DejaVuSans-Bold.ttf
sudo curl $URL/fonts/LED.ttf -o /opt/basketclock/fonts/LED.ttf
sudo curl $URL/image/hageland.png -o /opt/basketclock/image/hageland.png
sudo curl $URL/image/handleidingScoreboard.png -o /opt/basketclock/image/handleidingScoreboard.png
sudo curl $URL/sounds/BUZZER.WAV -o /opt/basketclock/sounds/BUZZER.WAV

## Install pygame
sudo apt install python3-pip -y
python3 -m pip install pygame

## Install dependencies
sudo apt install libsdl2-2.0-0 libsdl2-ttf-2.0-0 libsdl2-mixer-2.0-0 libsdl2-image-2.0-0 -y
sudo apt install libegl-dev -y

## Install RaspAP
curl -sL https://install.raspap.com | bash -s -- --yes --path /var/www/html --yes --restapi 0 --wireguard 0 --adblock 0 --openvpn 0 --provider 0

